Jay/scale changes
racker/ceres-tenant-routing-service pull request #8
Opened 2019-06-19 23:54 UTC by mritunjaykumar

2019-06-24 20:06 UTC, zack-shoylev requested changes

2019-06-24 20:06 UTC, zack-shoylev commented on src/main/java/com/rackspacecloud/metrics/tenantroutingservice/controllers/GlobalExceptionHandler.java
>      private static Logger LOGGER = LoggerFactory.getLogger(GlobalExceptionHandler.class);
Consider switching those to annotation. It should be a fairly painless search-and-replace

2019-06-24 20:06 UTC, zack-shoylev commented on src/main/java/com/rackspacecloud/metrics/tenantroutingservice/config/RoutingServiceImplConfiguration.java
> +    private String influxDBScalerUrl;
Consider making this a URL and potentially using a class with @ConfigurationProperties, like https://github.com/racker/ceres-ingestion-service/blob/master/src/main/java/com/rackspacecloud/metrics/ingestionservice/influxdb/config/BackupProperties.java as long as it's not overkill.

2019-06-24 20:06 UTC, zack-shoylev commented on src/main/java/com/rackspacecloud/metrics/tenantroutingservice/services/RoutingServiceImpl.java
> +        int hashCodeSum = tenantId.hashCode() + measurement.hashCode();
When combining hashcodes like that, use xor (^) instead of addition (+).

2019-06-24 20:06 UTC, zack-shoylev commented on tenant-routing-service.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Is this iml file needed here? Usually *.iml should be in gitignore, unless i'm missing something

2019-06-25 18:17 UTC, mritunjaykumar commented on src/main/java/com/rackspacecloud/metrics/tenantroutingservice/services/RoutingServiceImpl.java
> +        int hashCodeSum = tenantId.hashCode() + measurement.hashCode();
Good find! Fixed now.

2019-07-01 17:52 UTC, zack-shoylev approved these changes

2019-07-01 18:04 UTC, merged